#pragma once
//TAG
#define HGUI_TAG_MAIN "HGUI_TAG_MAIN"
//SHADER
#define HGUI_SHADER_BUTTON "HGUI_SHADER_BUTTON"
#define HGUI_SHADER_SPRITE "HGUI_SHADER_SPRITE"
#define HGUI_SHADER_TEXTAREA "HGUI_SHADER_TEXTAREA"
#define HGUI_SHADER_FRAMEBUFFER "HGUI_SHADER_FRAMEBUFFER"
//TEXTURE
#define HGUI_TEXTURE_BUTTON "HGUI_TEXTURE_BUTTON"
//FRAMEBUFFER
#define HGUI_FRAMEBUFFER_POST_PROCESSING "HGUI_FRAMEBUFFER_POST_PROCESSING"
//FONT
#define HGUI_FONT_NASA "HGUI_FONT_NASA"
//CURSOR
#define HGUI_CURSOR_ARROW "HGUI_CURSOR_ARROW"
#define HGUI_CURSOR_IBEAM "HGUI_CURSOR_IBEAM"
#define HGUI_CURSOR_CROSSHAIR "HGUI_CURSOR_CROSSHAIR"
#define HGUI_CURSOR_HAND "HGUI_CURSOR_HAND"
#define HGUI_CURSOR_HRESIZE "HGUI_CURSOR_HRESIZE"
#define HGUI_CURSOR_VRESIZE "HGUI_CURSOR_VRESIZE"