#pragma once
//OpengGL library
#include <glad/glad.h>
#include <GLFW/glfw3.h>
//STL library
#include <iostream>
#include <fstream>
#include <sstream>
#include <vector>
#include <memory>
#include <array>
#include <exception>
#include <map>
#include <utility>
#include <functional>
#include <tuple>
#include <thread>
#include <chrono>
#include <algorithm>
#include <initializer_list>
#include <variant>
#include <numeric>
//STBI library
#include <stbi/stb_image.h>
#include <stbi/stb_image_write.h>
//GLM library
#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include <glm/gtc/type_ptr.hpp>
//FreeType library
#include <ft2build.h>
#include FT_FREETYPE_H
//HGUI CONSTANTS
#define HGUI_VERSION_DEBUG